services:
  flask:
    build: .
    container_name: flask-app
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/backendflask
    depends_on:
      - redis
      - mysql
    working_dir: /backendflask
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_APP: app/app.py


  worker:
    build: .
    container_name: flask-worker
    env_file: .env
    volumes:
      - .:/backendflask
    depends_on:
      - redis
      - mysql
    working_dir: /backendflask
    command: celery -A app.tasks.celery_app.celery worker --loglevel=info

  beat:
    build: .
    container_name: flask-beat
    env_file: .env
    volumes:
      - .:/backendflask
    depends_on:
      - redis
      - mysql
    working_dir: /backendflask
    command: celery -A app.tasks.celery_app.celery beat --loglevel=info

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: flaskcar
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
