services:
  fastapi:
    build:
      context: .
    container_name: fastapi-app
    command: ./scripts/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/backendflask
    networks:
      - fast-network

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: ./scripts/celery_worker.sh
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/backendflask
    networks:
      - fast-network

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: ./scripts/celery_beat.sh
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/backendflask
    networks:
      - fast-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - fast-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fastcar
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fast-network

volumes:
  mysql_data:

networks:
  fast-network:
    driver: bridge
