"""Add role to user

Revision ID: 911318ddae42
Revises: 
Create Date: 2025-08-05 13:09:53.307329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911318ddae42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
